---
- name: Distribute SSH keys to server hosts
  hosts: server, desktop
  gather_facts: no
  become: yes

  pre_tasks:
  - name: Set host-specific credentials for servers
    set_fact:
      ansible_user: "{{ server_creds[inventory_hostname].user }}"
      ansible_password: "{{ server_creds[inventory_hostname].password }}"
      ansible_become_password: "{{ server_creds[inventory_hostname].become_pass }}"
    when: inventory_hostname in groups['server']
    # when: "'jetsons' not in group_names" works fine too.
  - name: Set host-specific credentials for desktops
    set_fact:
      ansible_user: "{{ desktop_creds[inventory_hostname].user }}"
      ansible_password: "{{ desktop_creds[inventory_hostname].password }}"
      ansible_become_password: "{{ desktop_creds[inventory_hostname].become_pass }}"
    when: inventory_hostname in groups['desktop']
      
  - name: Set Ansible connection variables
    set_fact:
      ansible_ssh_user: "{{ ansible_user }}"
      ansible_ssh_pass: "{{ ansible_password }}"

  tasks:      
    - name: Copy ansible ssh key to remote hosts
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/ansible_id_ed25519.pub') }}"
    - name: Copy ssh key to remote hosts
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"